### ISSUE TITLE
Allow setting data asynchronously

### ISSUE THREAD

**Issue by bahrus** [alenaksu/json-viewer#1]
Excellent component!

I find that if I do a dynamic import of your library, and while the import is downloading, set data (before the custom element has had the chance to get registered), the data is lost after the component is initiated.  

You might find [this document](https://developers.google.com/web/fundamentals/web-components/examples/howto-checkbox) helpful, search for "_upgradeProperty()"

**Comment by alenaksu** [comment]
Hey @bahrus, 
I'm glad you like it.

That's a good point and thank you for the link. 
I'm not sure it is going to work due to the way the attributes and properties are handled by the library I used, but I'll take a better look.

Meanwhile, have you already tried using the attribute instead?

```html
<json-viewer data="{ &quot;json&quot;: true }"></json-viewer>
```

**Comment by bahrus** [comment]
Ah yes, using innerHTML seems to work.
