### ISSUE TITLE
search always scrolls document.body

### ISSUE THREAD

**Issue by Terhiman** [alenaksu/json-viewer#10]
Even though my <json-viewer id="json"></json-viewer> element is deeply embedded in my html page structure, when I search for a value using viewer.search() it scrolls the whole document.body not the viewer element causing vertical page movement.

Similarly when initially loading the viewer with data it scrolls document.body around 20 pixels to the left.

**Comment by alenaksu** [comment]
Hi @Terhiman could you please provide a link to a codesandbox or whatever you prefer to replicate the bug?
