### ISSUE TITLE
How to use in with just index.js?

### ISSUE THREAD

**Issue by weirdyang** [alenaksu/json-viewer#13]
I tried the example, however the component just displays “null”.

I referenced the index.js and css files from the build folder, are those the wrong files?

**Comment by alenaksu** [comment]
Hi @weirdyang, could you provide an example that replicates the issue?

Also please take a look at this working example: https://codesandbox.io/s/staging-resonance-p79fx?file=/index.html

**Comment by weirdyang** [comment]
Thanks! fixed it by moving the script tag to the footer.

**Comment by alenaksu** [comment]
I see what was going on in your case, the component gets initialized as soon as the parser goes through the open tag, before the its children get parsed as well.

for more info, if you are interested: https://github.com/WICG/webcomponents/issues/551

**Comment by weirdyang** [comment]
Hey
Thanks for taking the time to reply and help me understand the root cause!
Really appreciate it.
