### ISSUE TITLE
Polymer 3 Support

### ISSUE THREAD

**Issue by zigic88** [alenaksu/json-viewer#22]
Hi,  can I use this component in polymer 3?
I've problem when import this component in my polymer 3 project. 
**Module not found: Error: Can't resolve '@alenaksu/json-viewer'**

Best Regards,
Reja

**Comment by alenaksu** [comment]
Hi @zigic88, it should work as it is a standard web component.

What version of the package are you using?

**Comment by zigic88** [comment]
Hi @alenaksu, thanks for your replies. 
I've found the problem in my polymer element declaration is json-viewer.js.
so I changed
import '@alenaksu/json-viewer/json-viewer.js';
into 
import '@alenaksu/json-viewer';
thanks for your great component.

Regards,
Reja
