### ISSUE TITLE
Possible issue outputting dates from nested object

### ISSUE THREAD

**Issue by andregoldstein** [alenaksu/json-viewer#26]
Hi there, thanks for this great component!

I'm running into an issue where sometimes my nested dates are showing as empty objects. I can't seem to pin down exactly why this is happening but will try and take another look at the source code.

For now I'm working around this by checking my structures for dates and formatting them ahead of time.

Thanks again (comparison with `JSON.stringify` below)

<img width="628" alt="Screenshot 2022-02-16 at 21 26 34" src="https://user-images.githubusercontent.com/7061578/154351493-e122a6dd-53ac-4e0e-9bdd-0b2ccfa6ce39.png">

**Comment by alenaksu** [comment]
Hi @andregoldstein, this is the expected behaviour as `Date` is not a valid JSON data type. I'll check further and update the issue

**Comment by andregoldstein** [comment]
Ah OK thanks, I thought that the library somehow took it into account anyway as sometimes the dates to display correctly

**Comment by alenaksu** [comment]
Closing in favor of #37
