### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by MariaCobretti** [alenaksu/json-viewer#29]
I cant get the demo to run 

this is what i see..
the console says [404] Not Found (/static/styles.js)

![image](https://user-images.githubusercontent.com/17946690/166895147-2b8442bb-d59a-4084-966c-93da7ca7188e.png)

**Comment by alenaksu** [comment]
Hi @MariaCobretti, are you trying to run the demo locally? If so, which command are you running?

**Comment by MariaCobretti** [comment]
npm run start

**Comment by alenaksu** [comment]
It's really strange, I don't see any issue.

Can you please add some more details? otherwise it would be really hard

- OS
- Node.js version
- Browser + version
- Console output of the command

**Comment by MariaCobretti** [comment]
windows 10
node v14.17.3
chrome browser, latest

here is the full log

![image](https://user-images.githubusercontent.com/17946690/167369060-ef6fdb42-4f06-4df6-a67a-891d10156110.png)

**Comment by alenaksu** [comment]
Thank you @MariaCobretti. 
I think I've found the issue and created a branch with the fix. Would you mind doing a quick test please?
[chore/fix-docs-windows](https://github.com/alenaksu/json-viewer/tree/chore/fix-docs-windows)

**Comment by MariaCobretti** [comment]
it is working!

did you get a chance to look at my other issue? I tried some stuff but couldnt fix it

**Comment by alenaksu** [comment]
Cool, thank you for checking, I'm merging the fix on master.

Regarding the other issue, let's move the conversation there.
