### ISSUE TITLE
BigNumber support

### ISSUE THREAD

**Issue by MariaCobretti** [alenaksu/json-viewer#30]
I am trying to display very large numbers but unfortunately they are getting rounded and cut by JavaScripts Number type..

any chance zu support BigNumber or a similar Type?

https://dev.to/fvictorio/a-comparison-of-bignumber-libraries-in-javascript-2gc5

**Comment by alenaksu** [comment]
hi @MariaCobretti, could you please provide a reproducible example?

**Comment by MariaCobretti** [comment]
sure..
https://alenaksu.github.io/json-viewer/#(%0A%20%20%20'bignumber!%20******%0A)*123%01*_

**Comment by alenaksu** [comment]
Thank you, the component leverages on the JSON.parse/JSON.stringify apis, which as far as I know, they don't support BigInt values 


From the [spec](https://tc39.es/ecma262/multipage/structured-data.html#sec-serializejsonproperty):
> 10. If [Type](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-data-types-and-values)(value) is BigInt, throw a TypeError exception.
