### ISSUE TITLE
Feature Request: CSS variable for padding

### ISSUE THREAD

**Issue by Canuckaholic** [alenaksu/json-viewer#32]
I would like to request a CSS variable be added for padding to the wrapping shadow DOM element (ul tag), so one can add a little space to the content, especially when it's long and needs to scroll. Thanks!

**Comment by alenaksu** [comment]
Hi @Canuckaholic, have you already tried styling the custom element? 
```css
json-viewer {
    padding: 1rem;
}
```

Let me know whether this is sufficient, otherwise we could think to add a `part` attribute to make it possible to apply custom styles to the UL tag.
