### ISSUE TITLE
Bug: When updating data dynamically, the library throws JSON.parse errors

### ISSUE THREAD

**Issue by AhsanAyaz** [alenaksu/json-viewer#33]
## What
When we're not using the `<json-viewer>` with any content, and rather just using the `data` attribute to dynamically update data. It throws the following error:
<img width="954" alt="Screenshot 2022-06-13 at 20 47 41" src="https://user-images.githubusercontent.com/9844254/173423651-209f43c8-307f-4ba2-9e1e-f7c80ad20736.png">

### Example usage:
```html
  <json-viewer class="p-4" data={props.response?.data}></json-viewer>
```

In this case, the error is thrown. 

### More context
I'm using this in a SolidJS app where the `data` attribute gets updated throughout the app's usage.

### Expected behavior
Should not throw an error in this case and should allow to just use of the `data` attribute for rendering.

**Comment by alenaksu** [comment]
Can you provide a reproducible example of the bug please?

I'm not familiar with SolidJS, but I think you are trying to set the `data` HTML attribute passing the object. HTML Attributes value should be strings, so the assigned value should be the string representation of the JSON data. 

Probably you can trying forcing the property instead
```jsx 
<json-viewer class="p-4" prop:data={props.response?.data}></json-viewer>
```

**Comment by AhsanAyaz** [comment]
Hey there,
I never pass an empty string to the `<json-viewer>` `data` attribute. You can see an example here:
https://github.com/code-with-ahsan/solidjs-rest-client/blob/main/src/components/RestClientOutput.tsx#L36

And you can definitely run the project and try it out.

**Comment by alenaksu** [comment]
Hi @AhsanAyaz, thank you for providing the repo. I was able to replicate the issue and I've created a PR. 
The fix I created is bit different from yours, please check it out and let me know if it's fine.
https://github.com/alenaksu/json-viewer/pull/35/

**Comment by alenaksu** [comment]
Hey @AhsanAyaz! Did you get a chance to take a look a the fix?
