### ISSUE TITLE
display property with html markup 

### ISSUE THREAD

**Issue by mbenolie** [alenaksu/json-viewer#48]
Hi, first I'd like yo thank you for  a great piece of code.

Some json objects may have properties that contain html markup, i.e. a link to a page, like in the address property below.

{
    "widget": {
        "debug": "on",
        "window": {
          	"title": "a window title",
            **"address": "<a href='abc.com'>Goto</a>",**
            "name": "main_window",
            "width": 500,
            "height": 500
        }
}
It would be nice, if the viewer can have a special csspart to render the markup as is . 

Thanks
Michel
mbenolie@gmail.com

**Comment by alenaksu** [comment]
Hi @mbenolie, the issue has been addressed with this new feature https://github.com/alenaksu/json-viewer?tab=readme-ov-file#custom-renderer, any feedback is welcome.
