### ISSUE TITLE
Search does not support regexes

### ISSUE THREAD

**Issue by Kylyi** [alenaksu/json-viewer#49]
**Describe the bug**
The search method does not support regex pattern.

<img width="626" alt="image" src="https://github.com/alenaksu/json-viewer/assets/19700450/5c4a07a8-1865-47f5-a650-890f68bbcefd">

**To Reproduce**

```
const search = 'some string'
const searchRegex = new RegExp(search, 'gi')

jsonViewer.search(searchRegex)
```

**Expected behavior**
As per doc, the `search` method should support regex patterns

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser Chrome

**Comment by alenaksu** [comment]
closed in #52
