### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by JakobTeske** [alenaksu/json-viewer#5]
The Readme has a badge, which indicates, that this project has an MIT license, but the license does not exist and the link in the README therefore returns a `404 Not found`. 

Is this intentionally, or should I make a pull request which readds the MIT License file?

**Comment by alenaksu** [comment]
Hi @JakobTeske, I haven't noticed the file was missing. If you open a pull request I would be happy to merge it :)

**Comment by JakobTeske** [comment]
I opened a Pull Request #6 :)

**Comment by alenaksu** [comment]
Merged, thank you!
